### ISSUE TITLE
Calendar is always reset to the current month instead of chosen one

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#105]
[Trac import]
Reported by: aperez
Original date: Wednesday, 08 September 2010 17:35

Currently, when one choses a day from a different month than the current one in the calendar, tasks for that day will be loaded, but the calendar will be reset to the current month. I would expect it to be kept in the month to which the chosen day belongs.

To reproduce:

 1. Choose any day from the previous month in the calendar (in fact, a day of any month other then the current one will do).

Result:

 1. Tasks for the chosen day load (ok).
 2. Calendar is reset to the current month.

Expected outcome:

 1. Calendar keeps showing the month the chosen day belongs to.

**Comment by jaragunde** [comment]
[Trac import]
Comment by: jaragunde
Original date: Wednesday, 22 September 2010 22:23

Fixed with commit ```add1869136e93df5f6ac19f895bf0167aaa08f78```.

**Comment by mrobinson** [comment]
I'm still seeing this issue. Maybe a regression?

**Comment by jaragunde** [comment]
I cannot reproduce the problem with any of the browsers I have at hand. Can you provide more details?

**Comment by jaragunde** [comment]
Identified as a different problem, a regression caused by #392.
