### ISSUE TITLE
Show current editing day in the layout over the tasks

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#115]
[Trac import]
Reported by: chema
Original date: Wednesday, 22 September 2010 15:14

If you change the calendar month you can't see the day that is being currenlty edited, because the only reference is the one in the calendar, current editing date should be showed in the page.

An idea could be put a tittle over the task lists.

**Comment by jaragunde** [comment]
[Trac import]
Comment by: jaragunde
Original date: Thursday, 23 September 2010 12:52

Although now the calendar shows the month to which the selected day belongs (that was in ticket #105 and it's fixed), adding a title would be a good idea.

**Comment by jaragunde** [comment]
[Trac import]
Comment by: jaragunde
Original date: Monday, 27 September 2010 12:28

This isn't a defect anymore, since now users can always see the selected date marked in blue on the side bar calendar.

**Comment by dmtrek14** [comment]
Closing since this is noted as no longer being a defect
