### ISSUE TITLE
Support for "get" URLs or links for queries

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#138]
[Trac import]
Reported by: agomez
Original date: Thursday, 10 February 2011 14:17

It is really helpful to have a way to copy&paste direct links to the queries.

Right now, those actions are done through "post" and is not possible to know which would be the proper URL.

**Comment by dmtrek14** [comment]
Since we are in the process of rewriting the API, there will be a full range of endpoints available in the future.
