### ISSUE TITLE
Improved feedback on error in the installation wizard.

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#149]
[Trac import]
Reported by: jaragunde
Original date: Sunday, 04 September 2011 16:23

The installation wizard only has two states: error or success. It would be great that the user received information of some common errors:
- No connection with the DB.
- Connection with the DB exists but phpreport user or database don't exist.
- postgres library for PHP is not installed (currently the wizard shows an empty message in this case).

**Comment by dmtrek14** [comment]
The installation wizard will be deprecated. 🧙🏻‍♂️
