### ISSUE TITLE
Middle-click on a date in tasks screen doesn't open that date in a new window

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#157]
[Trac import]
Reported by: jaragunde
Original date: Monday, 19 September 2011 19:16

The days in the calendar in the left bar of tasks screen are actual links, but they can't be middle-clicked to be opened in a new page. You can, instead, right-click and select 'Open in a new tab' but that's on more click than strictly necessary ;) .

It seems that the framework is capturing the middle-click event, preventing its default behaviour.

**Comment by jaragunde** [comment]
[Trac import]
Comment by: agomez
Original date: Wednesday, 28 September 2011 22:28

Middle-click is working OK for me.

Has there been any change lately?

**Comment by jaragunde** [comment]
[Trac import]
Comment by: jaragunde
Original date: Tuesday, 24 November 2015 14:19

Reproducible in Chromium and Epiphany, probably in all !WebKit-based browsers. Not reproducible in Firefox.

**Comment by jaragunde** [comment]
The bug only happens with the Epiphany browser now (maybe also with Safari).

**Comment by jaragunde** [comment]
When studying #411 I realized that the select event is launched when days are left-clicked, which runs the listener code that loads a different date. I suspect that the browsers that can reproduce this bug are triggering the datepicker select event on middle-click too.

**Comment by jaragunde** [comment]
Works for me in Chromium 105.0.5195.125 and Firefox 107.0.

**Comment by jaragunde** [comment]
Hmm, still reproducible in WebKitGTK 2.38.2 (Epiphany/GNOME Web 43.0). I don't know if Safari would behave the same.

I leave this closed until we find affected users.

**Comment by dmtrek14** [comment]
We are in the process of rewriting the frontend for tasks. Any outstanding bugs and enhancements for the old interface will be taken into account as we implement the new design.
