### ISSUE TITLE
Hour compensations screen shows user ids instead of names in some cases

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#166]
[Trac import]
Reported by: jaragunde
Original date: Monday, 13 February 2012 10:27

This happens randomly, I think it's because sometimes the data store with the users is loaded when the grid is already rendered.

We have to delay the render of the table until all the data has been loaded.

**Comment by dmtrek14** [comment]
This doesn't seem to be happening anymore. Closing for now.
