### ISSUE TITLE
Error status of AJAX responses is not checked correctly

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#169]
[Trac import]
Reported by: jaragunde
Original date: Friday, 17 February 2012 17:55

Right now, if an AJAX operation is performed (for example, saving a project) and the service returns an error field, the user doesn't see an error message but an OK message instead. That's because we rely on the default error check of ExtJS stores, which passes when the HTTP response code is 200.

Right now, in case of error we return a result like the following in a HTTP 200 response:

```
<return service='updateAreas'>
    <error id='3'>Forbidden service for this User</error>
</return>
```

We should implement the callbacks in a way that this field is checked, and if it's present provide feedback to the user with the message returned by the service.

These are the steps to reproduce this bug:
- Login with a normal user.
- Go to Project management page (Data management -> Projects).
- Edit an existing project. When you click 'Accept', an OK message is returned, but data aren't actually saved.
- If you refresh the page, you will see that your changes aren't saved.

Finally, the steps above are one way to reproduce the bug, but in could happen in any screen with an ExtJS Store + !XmlWriter exchanging data with !PhpReport services.

**Comment by jaragunde** [comment]
[Trac import]
Comment by: jaragunde
Original date: Friday, 17 February 2012 19:26

After the commit 35908a034d1c1d5cb0ad6d86214bdf08ae41a299 (permissions review) the steps to reproduce this bug can't be done any more, but you can always revert this patch, or allow normal users into project management screen again doing the needed changes to config/permissions.php.

**Comment by dmtrek14** [comment]
Since we are rewriting the app and everything will be handled with a more robust API that produces json as well as a frontend with better validation, this issue will be solved by these changes.
