### ISSUE TITLE
[API] password shouldn't be passed a URL parameter

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#223]
[Trac import]
Reported by: pnormand
Original date: Monday, 09 September 2013 12:31

Even if the phpreport website is using https, passing the password in clear text as a URL parameter to loginService.php presents a huge security risk

- password can be leaked from Apache logs
- if client uses a proxy the password can also be logged and leaked from those logs

Usually the password is at the very least hashed before going through the network and it's not passed as a URL parameter.

**Comment by tonythomas01** [comment]
I see that loginService.php accepts the same as: 
`  $userLogin = $_GET['login']; ` and ` $userPassword = $_GET['password']; 

Do you recommend that I change the method to accept only POST requests ? That might affect any clients already using the Login API (I'm not aware of?)

**Comment by jaragunde** [comment]
We would like the authentication data to be sent using the [HTTP authentication headers](http://php.net/manual/en/features.http-auth.php), and forbid the usage of both GET and POST to sent credentials.

**Comment by tonythomas01** [comment]
Pull #256 acknowledge the same.

**Comment by jaragunde** [comment]
Actually, HTTP authentication didn't seem to be working properly before your patch! This fixes it:
```
commit f49a488597e399bfe50089bbaaca1c27d371902d
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Wed Jul 13 20:15:12 2016 +0530

    [#223] Force HTTP Authentication for login service
    
    The extra check for empty username and password will make sure that
    the dialog is asked again in case the user enter empty string.
```

Thank you!
