### ISSUE TITLE
Tasks created too soon cannot be saved

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#225]
[Trac import]
Reported by: jaragunde
Original date: Monday, 23 December 2013 11:53

If you press the new task or a template button to create a task before the load operation has been completed, that task is not properly added to the list and it cannot be saved.

Steps to reproduce:
1. Go to some date that contains saved tasks.
2. Place the mouse over one of the new task buttons.
3. Reload and press the button immediately, before the tasks are loaded.
  * If you did it correctly, the new task will be the first one in the list.
4. Fill the new task and press save. Nothing happens.

**Comment by jaragunde** [comment]
To easily reproduce this bug, add a [sleep()](http://php.net/manual/en/function.sleep.php) call in the `getUserTasks` service. You will have all the extra time you want to create the new task following the steps above.

**Comment by tonythomas01** [comment]
I find this from the apache error logs on trying to save. Might be uesful. 
`[Tue Jul 12 22:43:10.620874 2016] [:error] [pid 17792] [client ::1:47641] PHP Notice:  Undefined index: sid in /var/www/igalia/phpreport/web/services/getOpenTaskStoriesService.php on line 33, referer: http://localhost/igalia/phpreport/web/tasks.php?date=2016-07-11
`

**Comment by tonythomas01** [comment]
Err. that seems to be unrelated. Looks like `newTask.id` is set to 1, when we click 'New' before load.

**Comment by tonythomas01** [comment]
Alright. More findings:

- Task created soon do not have a `store:` value in it  (from console.log after creation), while others had the store value S 
- That would mean that `myStore.add(newTask)` is failing to add the same.

**Comment by jaragunde** [comment]
Fixed by:
```
commit 5e4497de23eba879e905b0ff42458fc34c17b982
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Fri Jul 15 13:48:53 2016 +0530

    [#225] Wait till all tasks have loaded before adding in the new task
    
    This is a rude way of fixing the bug, but the right id seems not to
    load when the 'New Task' and a template is clicked before page load
```

Thank you!

**Comment by jaragunde** [comment]
There were some JS errors due to this patch, solved with:
```
commit 495c0b6c427eb57bd25274ec33fc0be41056cfae
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Tue Nov 1 20:10:48 2016 +0100

    [#225] Prevent JS errors when creating tasks before everything is loaded
    
    We should prevent the rest of the button callback from being executed
    when tasks store is not loaded yet.
