### ISSUE TITLE
Overtime control

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#243]
Include status information related to the target timetable for someone to fullfill for their acc hours for a defined period. Everyone could see how they would be doing in terms of acc hours reduction/increasing. The information would be present everytime you are tracking your time.

The task would imply to define a acc hours goal at a defined period, for each user. For example:

- 0acc hours at the end of the year, 
- 100acc hours at the end of the year.

The process would calculate the ideal timetable for each period of the month applying a lineal interpolation of hours. For instance, the ideal week timetable for someone could be 35.5 hours/week. So if in the current week, month or day someone has dedicated more or less than the estimated optimal scheduling, this person would see a -1h less or +25m more.

Different colors will be used: green or red depending on if someone is close to their goal.

**Comment by jaragunde** [comment]
> The task would imply to define a acc hours goal at a defined period, for each user. For example:
> * 0acc hours at the end of the year,
> * 100acc hours at the end of the year.

I think it's simpler to implement, and even more useful, to define goals like this:
* in the period between 1st of January and 31st of December, I want to do 0 extra hours (I don't want to increase or reduce the total of accumulated hours).
* in the period between 1st of January and 31st of December, I want to do -50 extra hours (I want to reduce my total of accumulated hours by 50).

**Comment by jaragunde** [comment]
This task is a bit complex, let's divide it in smaller parts. This would be the first step.

I would assume everyone's goal is 0 acc hours at between the first and the last day of the year. It means that the application should get these data:
* the number of _workable hours_ between the first and the last day of the year.
* the number of _worked hours_ since the first day of the year until the current date.

The data above can be extracted from the existing _Acc hours report_. Then, the application should:
* calculate the number of _hours left to be worked_, this is just: workable - worked.
* calculate the number of weeks since the current date until the end of the year.
* divide the hours left between the number of weeks. This is the number of hours the user should work per week to fulfill their goal at the end of the year.

The number of hours to be worked per week should be presented to the user in the _User work summary_ box.

**Comment by tonythomas01** [comment]
I would start by creating a new menu entry under Reports -> My Goals, which can let the user set a from time, to time and extra hours he plan to work. This should go into a separate db table too where the extra time can take negative values too.

**Comment by jaragunde** [comment]
I wouldn't add a new entry in the menu to define this, I think it would be enough to have a new tab in data management -> users -> user histories. You could reuse some classes like `BaseHistoryVO`.

**Comment by jaragunde** [comment]
```
commit 014278fb828ba9407709ce5daf89fbbaf20c821a
Merge: 894be41 e9fd963
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Wed Aug 17 18:19:47 2016 +0200

    [#243] Implement overtime control
    
    Calculates which should be the weekly goal for a user to meet certain goals
    regarding accumulated hours.
    
    By default, the goal is the user should end the year in course with 0
    accumulated hours since the beginning of the year. Per-user goals may be
    customized by an admin user, just like the journey or city histories.
    
    (Merge pull request #274 from tonythomas01/overtime-control)

commit e9fd963a76510745600c8c6b597d37684dee1e20
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Wed Aug 17 21:19:28 2016 +0530

    [#243] Manually set default goal of 0 extra hours, when no goal is specified

commit 47e87f2fb2b041d4d35d8b953d3fa486b769a27a
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Fri Aug 12 21:29:25 2016 +0530

    Adjust initdate calculation to respect current date too

commit 78528269e72f7fe3e053c7c587d0f31a5d7cc881
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Fri Aug 12 18:50:59 2016 +0530

    Make the goal finder recalculate goal hours by respecting work done

commit ff4565f0810b1c9ebf6e257ef11b8d8110346bfa
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Fri Aug 12 15:23:11 2016 +0530

    Allow only one user goal for any given date, respect goal end dates

commit f51caef97d04293d7713e600742d0fe70176d2b0
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Thu Aug 11 22:03:13 2016 +0530

    Make the Goal finder calculate week difference from the start of week

commit 46c61c7bbb4b9403fac105e710244173a4488286
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Thu Aug 11 00:28:28 2016 +0530

    Improve the accuracy of the Goal finder, improve the number of week calculations
commit 07d3027726ae1054281ef4dd9a80db12f39ad5f5
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Wed Aug 3 11:02:08 2016 +0530

    Make the goal finder for the week respect weekly goal settings
    
    Logic Implemented:
    
    1 - Select the weekly goals setup for the user, which the current date falls
        in between
    2 - For each goal, find out how many extra hours were set, and how many weeks
        it was originally planned for
    3 - From step 2, get the hours the worker should work for each week by dividing
        the goal hours by original weeks in between
    4 - Add this sum to the original weekly goal when no extra goal is set

commit 0083a03f6d4e014abbadc75e4f45c994b961f89e
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Mon Aug 1 14:24:43 2016 +0530

    [#243] WIP: Implementation wihout respecting goal set, and only the working hours defined
    
    This patch  assume everyone's goal is 0 acc hours at between the first and the last day of
    the year. It takes in (as per jaragundes comment in #243):
    
    * the number of workable hours between the first and the last day of the year.
    * the number of worked hours since the first day of the year until the current date.
    
    and:
    
    * calculate the number of hours left to be worked, this is just: workable - worked.
    * calculate the number of weeks since the current date until the end of the year.
    * divide the hours left between the number of weeks. This is the number of hours the user should work per week to fulfill their goal at the end of the year
    
    and shows the same in tasks.php
    
    Update documenation, modify license headers, remove copy pasted comments

commit c798f943379caaf282b2be8ee5b5174a42cc9027
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Sat Jul 30 13:00:30 2016 +0530

    [#243][WIP] Implement intial table and user interface to take in extra hours from user

**Comment by jaragunde** [comment]
I found several problems with the current implementation when testing it with real data:
* In `getWorkedHoursInThisJourneyPeriod` calculations, the start date should be the goal start. Actually, this method should be renamed.
* In `getWeeksInBetweenDates`, we should use `ceil` to round the number of weeks. For example, if you set a goal between Jan 4 and Dec 31, it will say there are 51 weeks in between.
* For the default case, we should not use the 1st of January because the algorithm may include the last week of the previous year when calculating worked hours. It's better to start in the first day of the week 1 of the year.

We need to double-check what happens when goal dates are set in the middle of a week. In general, I'm inclined to force the goal start to always be in the beginning of the week, and the goal end in the end of the week.

**Comment by jaragunde** [comment]
```
commit 2a51e7a46395231b97522659ca23434aa56fa3b8
Merge: 7658175 26a2d2a
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Tue Aug 23 11:18:43 2016 +0200

    [#243] Improve the accuracy of overtime-control functions
    
    Fixes some calculation and precision errors and cleans up the code.
    
    (Merge pull request #287 from tonythomas01/overtime-control-fix)

commit 26a2d2a214aee7fe1972756cd570160f5e5ea6dd
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Mon Aug 22 23:53:21 2016 +0530

    Cleanup overtime control implementation functions and backend DAO

commit 920ba27a380445467a1f651ec6a33b64d423a1dc
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Mon Aug 22 23:32:02 2016 +0530

    [#243] Fix various issues in calculating weeks in user goal, increase precision

commit c66747abfc1b989d342dac74c08a2e3ee12c93f7
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Mon Aug 22 12:06:30 2016 +0530

    [#243] Improve the accuracy of overtime-control functions
