### ISSUE TITLE
Create a new simplified alternative UI to track hours

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#251]
Description: The idea consists of implementing a new screen to track time with a month view, with a row per project and where you do not have not to insert the start-end times for tasks (this would be optional).

It would something similar to this LibrePlan view:

![monthly-timesheets](https://cloud.githubusercontent.com/assets/2900877/16560162/ec4ed74a-41f1-11e6-9ddd-a061fd577a04.png)

Rationale: It provides several advantages:
- It increases the speed to fill the phpreport and reduces the amount of repeated data to insert.
- It improves to know the total amount of time dedicated in projects to the people which makes easier the follow-up and auto-control.
- The start and end fields are not needed to track the time and they are never used in the reports.

Assessment: It implies to change the data model to make optional the start and end date, replacing them with the duration of the task.

**Comment by dmtrek14** [comment]
We will be opening a Project in GitHub soon for the rewrite of the frontend, so closing this as we have a new design to work from.
