### ISSUE TITLE
Add previous/next day buttons at the bottom of the tasks

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#252]
Description: At present to change of day, you have to look in the calendar and select the date you want to move. The feature consists of adding these buttons at the bottom of each task. The buttons should be also navigable with the keyboard.

Rationale: To click the exact dates in the calendar to navigate to previous and next days is slightly uncomfortable. With this feature, this can be solved.

**Comment by tonythomas01** [comment]
Rather than putting it at the bottom of every task, we can use http://docs.sencha.com/extjs/3.4.0/#!/api/Ext.Panel-cfg-tools to put it somewhere neat at the top of page, with tooltips too! Looks good ? 

![selection_193](https://cloud.githubusercontent.com/assets/4214481/18408413/c1efcd52-774c-11e6-9149-cdb2e3730fde.png)

**Comment by jaragunde** [comment]
```
commit e03f9b68bc0705b84b6a239caedf5da4b4266497
Merge: 25f85ea d60527c
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Tue Oct 25 20:09:22 2016 +0200

    [#252] Add previous/next day buttons and keyboard shortcuts
    
    (Merge pull request #298 from tonythomas01/add-next-prev-buttons)

commit d60527c16a9da966a64aa56c1cc586124cbdb0b2
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Mon Oct 24 19:35:03 2016 +0200

    Remove all custom tabIndex markers

commit 25bb3caf3e5545deecdb6ece5d3e23c963bf3008
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Wed Sep 14 15:38:30 2016 +0530

    [#252] Add navigation buttons and kill navigation while inputs or textarea in focus

commit f3c5b53eee56359dce5bee3f858ef3352afbecfe
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Tue Sep 13 17:32:12 2016 +0530

    [#252] Allow navigation to prev/next on keyboard left/right clicks
