### ISSUE TITLE
Include the description of the task as part itself of the Template task

### ISSUE THREAD

**Issue by psaavedra** [Igalia/phpreport#265]
Please, add the content of the Description text area as the description of the Template task itself intance of use ir to add the Template task title.

In the attached image, you can see an example of how this feature could looks:

![screenshot at 2016-07-22 11 44 30](https://cloud.githubusercontent.com/assets/376838/17053580/ff29536c-5002-11e6-9bc1-e8ca82698213.png)

Finally, I would suggest use the JS prompt (or something similar) to introduce the title of the Template task: http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_prompt

**Comment by jaragunde** [comment]
For the record, the template table in the database already has a field for the task text, and the web services accept it as a parameter (in the ongoing implementation of #254). We would only have the UI part missing.

**Comment by jaragunde** [comment]
Let's also check if there is an Ext JS widget we could use instead of the JS prompt, the same way we are using Ext JS pop-ups instead of standard ones.

**Comment by jaragunde** [comment]
```
commit 9e3bd9b0166e6042560eeaed8f95e576b3555485
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Wed Jul 27 15:01:39 2016 +0530

    [#265] Include description of the task too in the template

commit 1df8c0e7977572dd25058efac15c42d81af5b901
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Wed Jul 27 10:32:52 2016 +0530

    [#254] Make sure the bool fields are set correctly for a fresh template load

commit 30d414e52e8261cb7539d82618d6f23d1aa7bc3c
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Tue Jul 26 22:30:44 2016 +0530

    [#265] Separately ask for template name using Ext message prompt
```

**Comment by psaavedra** [comment]
Thanks!
