### ISSUE TITLE
Make Project input wider on project details page

### ISSUE THREAD

**Issue by tonythomas01** [Igalia/phpreport#266]
Originally reported by @mrego 

> 
Could we make the Project input wider on project details page?
https://.../web/projectDetails.php

> Some projects have long names and you cannot read them completely in the
current input.

Probably will have to make both input boxes wide as well!

**Comment by jaragunde** [comment]
```
commit 9dcdaba041948134aeeff9a38ab34f433e578f3f
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Sat Jul 23 14:47:42 2016 +0530

    [#266] Make Project input wider on project details page
```

**Comment by mrego** [comment]
Thanks for the fix.
If possible I'd make it even a bit wider, I've been working with some projects with very long names it seems. :)

**Comment by tonythomas01** [comment]
I took the largest from `phpreport.igalia.com` and tried making the box long enough for fitting it :)

**Comment by jaragunde** [comment]
```
commit 76605a89ed838b4dd18bc9b5102afc676de387d6
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Wed Aug 17 15:04:56 2016 +0530

    [#266] Make the project input box still wider, no more clipping
