### ISSUE TITLE
PHP Warning - incorrect filename - TempatesVO

### ISSUE THREAD

**Issue by tonythomas01** [Igalia/phpreport#273]
`PHP Warning:  include_once(): Failed opening '/var/www/igalia/phpreport/web/services/../..//model/vo/TemplatesVO.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/igalia/phpreport/model/facade/TemplatesFacade.php on line 35, referer: http://localhost/igalia/phpreport/web/tasks.php?date=2016-07-30`

**Comment by jaragunde** [comment]
```
commit 046cc0c0277d24a2365cdbd183df60d622f70eb5
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Mon Aug 1 14:24:46 2016 +0530

    [#273] Fix incorrect filename - TemplatesVO => TemplateVO
```
