### ISSUE TITLE
[Tracking] Unused code in phpreport codebase

### ISSUE THREAD

**Issue by tonythomas01** [Igalia/phpreport#291]
- SectorDAO/PostgreSQLSectorDAO.php:    public function getCustomers($sectorId) { }

**Comment by tonythomas01** [comment]
`getAllCustomProjectsService` is not used anywhere.

**Comment by jaragunde** [comment]
```
commit 60ed64fc6eb61c9dc6242db2e808d141be997e26
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Fri Sep 16 23:49:29 2016 +0530

    [#291][#297] Remove unused getAllCustomProjectsService from codebase

**Comment by jaragunde** [comment]
We have been removing a lot of unused code recently. Sadly, we haven't been updating or linking this ticket, so it's not really useful to keep it open.
