### ISSUE TITLE
Template tasks may delete new tasks

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#293]
I've just found a problem in the implementation of #247, in particular this part:

> b) delete the empty task when copying tasks from other days or creating the first task from a template.

Steps to reproduce:
1. Open a new, empty day.
2. Fill the empty task with some init/end time, project, etc.
3. Now click on a template button to add a second task.

Expected result: the template task is added, so there are two tasks now.
Actual result: the template task deletes the existing task, even when it's not empty any more.

**Comment by tonythomas01** [comment]
Yeah. I see that, the problem being - isDirty is true until the task is automatically or manually saved :( Let me see how this thing can be fixed!

**Comment by jaragunde** [comment]
```
commit 29e66f537a08ff034319202fa1d2ab33a82c8eb0
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Tue Sep 6 11:33:53 2016 +0530

    [#293] Fix: Template tasks may delete new tasks
