### ISSUE TITLE
Unify the different getProject services

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#297]
There are several services to retrieve data about projects in the system, with small differences in their API. These are the services I've found on a preliminary look:

* ~~getAllCustomProjectsService.php~~ - after #304 
* ~~getAllProjectsService.php~~ - renamed as `getProjectsService.php` after #305 
* ~~getFilteredCustomProjectsService.php~~ killed in #305
* getProjectService.php -- needs to be renamed to `getProjectDetails.php` 
* ~~getProjectsAndCustomersForLoginService.php~~ killed in #305 

The goals of this task are:
* Identify all the services that gather data from projects.
* Check the API of each of those services and design one service that covers all the use cases (or a couple of services, at most), removing the original ones.
* Change the frontend code to make use of the new service or services.
* The redesign will also probably propagate downwards in the application model. Check if it's possible to unify several facade or dao operations.

**Comment by tonythomas01** [comment]
so - there is a problem here - probably we should have two service here: 

1. a service which get the results from a single project - like the `getProjectService.php` - maybe named as `getProjectDetailsService.php`
2. another service which can return details of multiple project - like the rest of the services. - maybe called as `getProjectsService.php`

**Comment by tonythomas01** [comment]
I am not touching `getProjectService` as it would end in a merge conflict with https://github.com/Igalia/phpreport/pull/301

**Comment by jaragunde** [comment]
```
commit 60ed64fc6eb61c9dc6242db2e808d141be997e26
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Fri Sep 16 23:49:29 2016 +0530

    [#291][#297] Remove unused getAllCustomProjectsService from codebase

**Comment by jaragunde** [comment]
```
commit 72ef73adb9009bc60a5af2f936bea497c3fd2df0
Merge: 2952636 88ca1d9
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Fri Oct 14 12:53:19 2016 +0200

    [#297] Clean up getProject* services
    
    (Merge pull request #305 from tonythomas01/unify-getProjects)

commit 88ca1d98da8c183603e102952123ecf48f8e00fc
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Fri Oct 14 12:26:50 2016 +0200

    [#297] Remove getFilteredCustomProjectsService from the codebase

commit 9a9ccbf9a93e0f00b2ffb97ff89088356d9d1094
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Fri Oct 14 11:54:59 2016 +0200

    [#297] Fix filter by customer name in projectsEvaluation

commit bb26cb8da6b562cafac1ca2bb912da509500ceb4
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Fri Oct 14 11:04:36 2016 +0200

    [#297] Show up only active projects in the tasks page

**Comment by jaragunde** [comment]
It seems that the simplest calls to getProjects (like from the tasks screen) are much slower now. That makes the user experience worse, let's not close this ticket yet.

**Comment by jaragunde** [comment]
Ooops, I just noticed the project evaluation report is not working as it should. It ignores worked hours and some other information that used to be part of the `CustomProjectVO`. This needs fixing too.

**Comment by jaragunde** [comment]
```
commit 639727a086a7abb9b4e05e528873efd4bf828472
Author: Tony Thomas <01tonythomas@gmail.com>
Date:   Wed Oct 19 18:49:09 2016 +0200

    [#297] Simplify query for tasks page with a returnExtendedInfo flag
    
    After PR#305 queries to getProjects service became too slow. It was
    because big queries were being run to satisfy the requirements of the
    project evaluation report.
    
    Now the slower query is hidden behind a flag which enables the service
    to retrieve dedication data from the project.
    
    Collaterally fixed project evaluation report, the DAO was not
    returning CustomProjectVO objects by mistake.

**Comment by jaragunde** [comment]
Related commit:
```
commit 7f94322d23811c528ef27324353376b10ada57e5
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Tue Nov 29 12:45:33 2016 +0100

    Add filter by customer id to getProjectsService

```
This filter used to exist in some of the old getProject services.
