### ISSUE TITLE
end time dropdown list scrolls itself back to the top if you wait

### ISSUE THREAD

**Issue by thejoshwolfe** [Igalia/phpreport#309]
steps to reproduce:

* While creating a new task, select a start time.
* Open the dropdown for the end time and scroll down a ways. (the end time textbox must be blank)
* Wait for 5 seconds.

Now the dropdown scrolls itself back to the top.

**Comment by thejoshwolfe** [comment]
My guess is that the scrolling is triggered by the autosave feature.

**Comment by jaragunde** [comment]
The source of this problem is the validation code that is triggered by the autosave feature. When time fields are validated against each other, the list of choices for the combo box is rebuilt, in consequence the position of the combo is reset.

**Comment by jaragunde** [comment]
This patch should fix this issue:
```
commit 25f85eac4e5aa9c6e7fa4f7bce9cfc6f95ed946d
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Fri Oct 21 18:09:45 2016 +0200

    [#309] Do not update the init/end times combos during the validation code
    
    Validation is run every time the autosave trigger is launched, which
    was causing the values of the combos to be reset, causing this problem
    in the middle of edition.
    
    Now, the values of the combos are set on the change callback.
