### ISSUE TITLE
Navigating away from an auto-generated blank task should not ask for confirmation

### ISSUE THREAD

**Issue by thejoshwolfe** [Igalia/phpreport#310]
Steps to reproduce:

* Click on a date where you don't have any tasks logged. You should see an auto-generated blank task with no start time and an end time of now.
* Click on a different date.

At this point you're prompted with a confirmation box that warns that you'll lose the data you entered if you leave the page. But since you didn't actually enter any information, the warning is a false alarm.

**Comment by jaragunde** [comment]
Fixed in #296.
