### ISSUE TITLE
Creating and deleting a blank task asks for confirmation before leaving the page even after saving

### ISSUE THREAD

**Issue by thejoshwolfe** [Igalia/phpreport#311]
Steps to reproduce:

* Go to any day where you have a task saved task (didn't test on a day with no task).
* Create a new task, and then delete it.
* Click "Save changes" if you want; it doesn't matter.
* Navigate to another day.

At this point you'll be prompted with the confirmation box for losing unsaved changes.

**Comment by jaragunde** [comment]
Fixed by #296! :)

**Comment by jaragunde** [comment]
FTR, that patch was not addressing this particular issue, but it rewrote the confirmation prompt logic in a way it now supports this case too.
