### ISSUE TITLE
Reduce/remove delay between typing and UI responsiveness

### ISSUE THREAD

**Issue by thejoshwolfe** [Igalia/phpreport#312]
Steps to reproduce:
- Select the start time box of a task and make sure there is no text in the box.
- Using the keyboard, type '0', '9', and then tab. Do all this very quickly.

If you typed fast enough, the start time box now says "00:15". If you typed slower, then the box says "09:00".

Could we perhaps remove this window of failure by making the UI instantly responsive?

**Comment by dmtrek14** [comment]
We are in the process of rewriting the frontend for tasks. Any outstanding bugs and enhancements for the old interface will be taken into account as we implement the new design.
