### ISSUE TITLE
end time box should not block suggestions from the start time box

### ISSUE THREAD

**Issue by thejoshwolfe** [Igalia/phpreport#313]
Steps to reproduce:
- In the end time box, type 01:00. (Sometimes this happens by mistake.)
- Make the box lose focus.
- Use the tab key to refocus the end time box (this probably works with just clicking too), and delete all the text with Backspace.
- Press shift+tab to select the start time box.

At this point the end time box says "01:00" again, even though you deleted the text.
- So tab back over to the end time box, (all the text gets selected), and type Backspace again. If you pause for a moment, you'll notice that there's a suggestion list that popped up, and "01:00" is selected. This seems to be why tabbing away fills in that time. So press Escape to close the suggestion list.
- Now type shift+tab to select the start time box, and notice that the end time box is still blank.
- Now type "09" or anything else, but don't make the start time box lose focus yet.

At this point, you should see that the suggested times for the start time are still limited to being before "01:00" (aka, "00:15", "00:30", "00:45").

A simple change to make this situation much better would be to not limit the start time suggestions by any existing end time. Then people can fill in the start time normally, and then fill in the end time afterward, and any initial value for the end time doesn't matter.

**Comment by dmtrek14** [comment]
We are in the process of rewriting the frontend for tasks. Any outstanding bugs and enhancements for the old interface will be taken into account as we implement the new design.
