### ISSUE TITLE
Don't automatically fill in the end time as the current time

### ISSUE THREAD

**Issue by thejoshwolfe** [Igalia/phpreport#314]
Somewhat related to #190 , I often want to record the start time of a task and save that, and then later record the end time of a task when i'm actually done with it. With this usecase, the automatically filled-in end time of now is not correct, and it's just in the way. (see #313 for a problem that sometimes happens related to this.)

Furthermore, I round times to 15 minutes, as the dropdowns suggest, so the automatic end time accurate to the minute is usually not a value i want on my time sheet at all.

And the situation is especially silly if you're creating a task for a day that isn't today.

My recommendation is to get rid of the feature entirely, and always leave the end time blank on newly created tasks. A compromise could be to round the current time to 15m. But most of all, you should not fill in the end time for tasks being created for a day that isn't today.

**Comment by jaragunde** [comment]
> My recommendation is to get rid of the feature entirely

This is a good idea, we aren't even respecting it completely; new tasks created from templates already come with both start and end time empty .

**Comment by jaragunde** [comment]
```
commit 3067b33a8eddd445ce3c5c8e7b3ab5683eede04f
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Fri Oct 21 16:57:22 2016 +0200

    [#314] Don't automatically fill in the end time as the current time
    
    Also, the check for the empty initial task has been modified to take
    into account the end time field, it wasn't taken into account because
    it used to be auto-filled.

**Comment by jaragunde** [comment]
I had forgotten about the tasks created with the 'clone' button:
```
commit 00d9bcbc25f6dcd8a0c330410e115abbae329331
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Tue Nov 1 19:39:55 2016 +0100

    [#314] Don't fill end time in cloned tasks
