### ISSUE TITLE
tabbing back and forther between start and end time boxes changes their values

### ISSUE THREAD

**Issue by thejoshwolfe** [Igalia/phpreport#315]
Steps to reproduce:

* Create a new task.
* Fill in the start time with "10:00" or some time before the automatically filled in end time.

And then:

* Tab over to the end time box. (meaning press the Tab key.)
* Tab back over to the start time box. (Shift+Tab)
* Repeat.

Depending on your timing, the times in the two boxes will change as you tab around getting earlier and earlier, eventually stabilizing around midnight.

This seems related to #309.

**Comment by thejoshwolfe** [comment]
More info on the timing: it's definitely related to autosave. When the task autosaves, the suggestion box pops up and chooses one of the selections apparently at random. Then tabbing away records that suggestion into the box. The change of value queues up another autosave, and the cycle continues.

**Comment by jaragunde** [comment]
I cannot reproduce this bug after the patch for #309. Could this have been collaterally fixed?

**Comment by thejoshwolfe** [comment]
I believe it was collaterally fixed. I cannot reproduce it anymore either.
