### ISSUE TITLE
Redesign task creation workflow

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#337]
There are currently several ways to create a new task:
* New task button on the side bar, which actually creates an empty task
* New task button on the bottom bar, which also creates an empty task
* The new task key combination, which also creates an empty task
* Custom templates on the side bar
* The "full-day task" permanent template on the side bar

I think we would improve the user experience if we sorted things in a more logical way and increased the convenience of the existing buttons.

First, we could group all the task-creation actions in the side bar like in the example below. We would rename the "new" button as "empty task":
![screenshot from 2016-12-01 20-14-40](https://cloud.githubusercontent.com/assets/2900877/20808613/8274565a-b803-11e6-9167-e3ae07674ecb.png)

Second, we would need to implement a pop-up window in which users could select if they want an empty task or a task from some template in a quick way. Users should be able to use this pop-up with the keyboard. This popup would be invoked when "new task" is invoked through the new task button on the bottom bar or through the new task key combination.

With these changes, we would get the following improvements:
* "New task" would mean any kind of new task, not only empty ones.
* Enhanced grouping in the side bar.
* Uniform access to templates.
* Task templates would be accessible via keyboard.

**Comment by dmtrek14** [comment]
We are opening a Project in GitHub and working on a new design implementation, so closing this.
