### ISSUE TITLE
Cloned tasks can contain URL-encoded text

### ISSUE THREAD

**Issue by mrobinson** [Igalia/phpreport#344]
If you create a task with the text ```"text"``` (that includes the double quotes) in the task story of task description field, the cloned version of that task has the text ```&quot;text&quot;.```

**Comment by jaragunde** [comment]
Sorry, I don't understand what's the problem here.

**Comment by mrobinson** [comment]
Ack. Github decoded my URL-encoded text. Take a look at the first comment again. The weird thing is that I don't see this issue any longer on the live site.

**Comment by jaragunde** [comment]
I've seen this bug happening, I had written `it's` in some task description and it was cloned as `it&apos;s`. To reproduce the bug, I think there must be some timeout involved. I left the page open for some hours and it happened when I came back. Then, I reloaded and tried again and things worked normally.

**Comment by jaragunde** [comment]
This is actually a duplicate of #85, which has specific steps to reproduce. Closing this bug.
