### ISSUE TITLE
Download as CSV doesn't work for viewUserDetails.php in Chromium 60

### ISSUE THREAD

**Issue by psaavedra** [Igalia/phpreport#362]
The Download as CSV file button in the viewUserDetails.php generates a empty document in Chromium (`Version 60.0.3112.78 (Developer Build) Built on Ubuntu , running on Ubuntu 17.04 (64-bit)`). 

The issue is not replicable for example in Firefox 54.0 (64-bit) nor Chrome Version 56.0.2924.87 (64-bit)

This issue requires of a second case.

**Comment by jaragunde** [comment]
I can reproduce this problem too, with a similar version of Chromium (60.0.3112.101).

**Comment by jaragunde** [comment]
It's working now on version 106.0.5216.6 (Official Build) dev (64-bit).

@anarute wrote a fix for this in commit e32b3df30a0e6c349d4d983c52fe08ed43d24545.
