### ISSUE TITLE
Task description not saved if pasted with mouse click, only if pasted with Ctrl+V

### ISSUE THREAD

**Issue by mcatanzaro** [Igalia/phpreport#372]
Task descriptions are not saved if pasted with a mouse click, only if pasted with Ctrl+V. To reproduce, create a new task on some day and set the Time and Project fields. Press the Save Changes button for good measure. Then paste something into the big description field by right clicking on it and selecting Paste from the context menu. Notice the Status indicator at the bottom says "No changes detected" even though I have pasted stuff there! Pressing the Save button does nothing. Switching to another day and back causes the description to disappear. In contrast, if I paste using Ctrl+V instead of the context menu, the Status indicator changes to "Pending changes." Guess: perhaps PhpReport is looking only for keyboard events to determine if a task has unsaved changes.

Browser: Epiphany 3.24.4 with WebKitGTK+ 2.18.0

**Comment by jaragunde** [comment]
Caused by a limitation of the UI framework we used; the "change" event (a wrapper for a number of browser events) is only triggered right before the blur event. The next version of the framework started sending "change" events as soon as change happens, but the upgrade is not trivial.

**Comment by jaragunde** [comment]
```
commit 28a93d2a718773f78d6c04c246c927fd46843185
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Mon May 28 19:27:06 2018 +0200

    [#372] Check for change events periodically.
    
    Instead of waiting until the blur event to check for changes and
    trigger the Ext change event, we setup a periodical task to look for
    changes and launch the event if necessary.
    
    Keyup event listeners can be removed now because the new change event
    covers that case now.
```
