### ISSUE TITLE
Issue with highlighted date when trying to change date with unsaved changes

### ISSUE THREAD

**Issue by Ms2ger** [Igalia/phpreport#385]
STR:

- Click on a day (e.g.: Feb 1st).
- Fill in some task, don't save changes.
- Click on another day (e.g. Feb 2nd).
- Get a popup from the onbeforeunload handler ("Sure you want to leave this page...?")
- Click "Stay on page"
- The tasks for Feb 1st are shown, but Feb 2nd is highlighted on the calendar widget

**Comment by dmtrek14** [comment]
We are in the process of rewriting the frontend for tasks. Any outstanding bugs and enhancements for the old interface will be taken into account as we implement the new design.
