### ISSUE TITLE
Add a button to fill a full holiday

### ISSUE THREAD

**Issue by pabelenda** [Igalia/phpreport#389]
At #327 a template button was added to ease the creation of a task with the correct start and end times so it would fill an entire work journey for the selected user and date.

This was intended mainly to fill holidays, but seems like the usage is broader. For that reason it would be useful then to create a template button that creates a full day task assigned specifically to the VACATIONS_PROJECT defined in the configuration.

**Comment by jaragunde** [comment]
Reviewed in #390.

```
commit 71d414634f69f2eacec1960f2812876b964c0302
Author: Pablo Abelenda <pabelenda@igalia.com>
Date:   Wed Mar 7 13:03:29 2018 +0100

    [#389] Add template button to fill a full holiday
    
    This template sets the init and end date so it fills the entire
    journey for the current date. It also sets the project to be the
    holiday project specified in config.php.
    
    It triggers a save operation immediately to speed up holiday
    creation.
    
    (Squash pull request #390 from Igalia/full-holiday-task-button)
```
