### ISSUE TITLE
Acc hours report fails when user lists returned by services don't match

### ISSUE THREAD

**Issue by mcatanzaro** [Igalia/phpreport#404]
The accumulated hours report at https://.../web/viewWorkingHoursResultsReport.php no longer works. Sometimes the Loading spinner appears and remains spinning forever, and sometimes it just doesn't appear. This is a recent regression, as I'm sure I was able to use it successfully a month or two ago.

![screenshot from 2018-05-20 14-31-26](https://user-images.githubusercontent.com/1424966/40282839-a3438784-5c3a-11e8-8717-73893a252532.png)

![screenshot from 2018-05-20 14-30-04](https://user-images.githubusercontent.com/1424966/40282840-a6e4dc58-5c3a-11e8-8f50-97efb599747e.png)

Tested (a) Epiphany Tech Preview and (b) Epiphany 3.28.1.1 with WebKitGTK+ 2.20.2. It works fine in Chromium.

I see two errors in my web inspector. The first one is:

```
[Error] TypeError: null is not an object (evaluating 'document.getElementById('header').scrollHeight')
	Global Code (viewWorkingHoursResultsReport.php:146)
```

but Chromium's web inspector shows this error too, so that's probably not the problem. Next error is:

```
[Error] TypeError: undefined is not an object (evaluating 'row2.get')
	move (viewWorkingHoursResultsReport.php:247)
	each (ext-all.js:25:1304)
	each (ext-all.js:32:6380)
	populate (viewWorkingHoursResultsReport.php:275)
	fire (ext-all.js:21:4407)
	fireEvent (ext-all.js:21:1423)
	loadRecords (ext-all.js:32:3653)
	onRead (ext-all.js:32:23257)
	(anonymous function) (ext-all.js:32:22453)
	handleResponse (ext-all.js:22:28124)
	f (ext-base.js:21:17846)
	m (ext-base.js:21:18304)
	(anonymous function) (ext-base.js:21:8610)
```

I'm guessing that's to blame, as I don't see that error in Chromium's web inspector.

**Comment by jaragunde** [comment]
The first error must be unrelated, it was reported as #399. Unfortunately, I cannot reproduce the second error using Epiphany 3.28.1.1 + WebKitGTK+ 2.20.2. Would you mind testing with a clean profile?

**Comment by mcatanzaro** [comment]
I tested this using 'epiphany -p' (fresh temporary profile).

**Comment by jaragunde** [comment]
I cannot reproduce the error, but the stack trace points to a mismatch between the lists of users sent by the holidays and the extra hours backend services, which theoretically could happen.

**Comment by jaragunde** [comment]
The error can be reproduced forcing the holidays service output to contain less users than the extra hours service. With the default DB contents, this can be done with:
```
--- a/web/services/getPendingHolidayHoursService.php
+++ b/web/services/getPendingHolidayHoursService.php
@@ -118,6 +118,7 @@
 
         foreach((array) $report as $key => $entry)
         {
+        if($key != "admin")
         $string = $string . "<pendingHolidayHours login='{$key}'><hours>{$entry}</hours></pendingHolidayHours>";
         }
 
```

**Comment by jaragunde** [comment]
```
commit 5c4e79a1b0b9a190ac1093a768f7fa0710e750e5 
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Tue Jun 5 14:36:09 2018 +0200

    [#404] Set empty holiday data in case it doesn't exist.
    
    If we cannot find a certain user in the data returned by the pending
    holidays service, we fill it with an empty string.

```
