### ISSUE TITLE
Do not reload tasks page when date is changed

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#421]
The tasks page should behave like a single page, asynchronous web application. By default, it would show the tasks of today, with today defined by the browser date. When a date is changed, the page should not be reloaded; instead, the tasks store object should asynchronously load the tasks saved in that date, the task panels should be removed and replaced by the newly loaded tasks, and any newly created tasks would contain the new date. To simplify the implementation, we could force that any save operation should be completed before changing the date or otherwise lost (like it happens now), but in the future it would be interesting that all the saving happened in the background.

**Comment by dmtrek14** [comment]
We are in the process of rewriting the frontend for tasks. Any outstanding bugs and enhancements for the old interface will be taken into account as we implement the new design.
