### ISSUE TITLE
Include future holidays in user tasks summary

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#436]
The user tasks summary has a field for "pending holidays". It would be more useful that this figure checked any used holidays in the year in course.

For example, if I'm in December, 1st and I have already filled my Xmas holidays in advance, that should be reflected in the "pending holidays".

**Comment by jaragunde** [comment]
Reviewed in #473:
```
commit 7a520f93a678ca9692d4cc1c5e342eea361c4b5f
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Sat Apr 25 17:03:19 2020 +0200

    [#436] Include future holidays in user tasks summary.

```

**Comment by hferreiro** [comment]
Maybe it would be helpful if the field label was something like "Pending to assign" (hopefully something shorter) to make it clear that it's different from the rest of the fields in the summary.

**Comment by jaragunde** [comment]
I don't know how to properly word it. To make things worse, we have a variety of behaviors in that box; "worked hours" -> "week" and "week goal" take into account tasks "in the future" inside the same week, but "extra hours" don't do the same and they vary even when moving between days in the same week...
