### ISSUE TITLE
Dates in reports are off by a day

### ISSUE THREAD

**Issue by 7h3ju57** [Igalia/phpreport#459]
The issue I'm facing is that the dates when generating a report are off by a day.

If I create a task on August 2 14:00, when I create my report, it will say that the task was created on august 1 14:00. Issue isn't present when exporting to csv from said report. Which makes me think that the issue is javascript.

I can probably help fix this if you can tell me where your dates are being passed to javascript.

![image](https://user-images.githubusercontent.com/2500972/62392842-7e19eb00-b536-11e9-8ecc-79acdf00378a.png)
![image](https://user-images.githubusercontent.com/2500972/62392862-8e31ca80-b536-11e9-8ea3-9c2d93019ab7.png)

**Comment by 7h3ju57** [comment]
just noticed #451 which is basically what is happening here.
I'm not sure if this is a timezone issue but the server is running in the same timezone as I am.

Any debugging I can try to determine where the issue is?

**Comment by jaragunde** [comment]
It would be great to check the data exchanged with the server in the network tab of the web inspector. The service is `web/services/getTasksFiltered.php`, you might also want to add some server-side logging in that file.

(PSA: I'll be away next week, sorry if I cannot reply you timely).

**Comment by 7h3ju57** [comment]
Response from getTasksFiltered
`<tasks><task><id>12</id><date` `format="Y-m-d">2019-08-02</date><initTime>00:15</initTime><endTime>01:00</endTime><hours>00:45</hours><story/><telework>false</telework><onsite>false</onsite><ttype/><text>dsfdfsdf</text><phase/><userId>2</userId><projectId>1</projectId><taskStoryId/></task></tasks>`

`

**Comment by jaragunde** [comment]
Thanks for the info. I'm afraid the problem is buried inside code of the Ext JS framework. In `userTasksReport.js`, we make use of the `Ext.data.XmlReader` to parse the XML returned by the service, and to display them in the grid we use a `Ext.grid.ColumnModel` to translate the data.

I think it's still somehow related with timezones. Under certain circumstances, a Date object created from a string can be assumed to be UTC, and it's later translated to the local time zone.

**Comment by jaragunde** [comment]
> I think it's still somehow related with timezones. Under certain circumstances, a Date object created from a string can be assumed to be UTC, and it's later translated to the local time zone.

I can confirm this suspicion. If I set my timezone to PST, I can reproduce the bug. From the JS console, this is what happens when I create a new Date object like this:
```
> new Date("2018-08-13");
Sun Aug 12 2018 17:00:00 GMT-0700 (Pacific Daylight Time)
```
It assumes the date object has the 0:00 time at UTC, which is then translated to PST when printed. The Ext JS framework must be creating the Date objects like this.

**Comment by jaragunde** [comment]
Oddly enough, if you use a different string format, result is different:
```
> new Date("2018-08-13");
Sun Aug 12 2018 17:00:00 GMT-0700 (Pacific Daylight Time)
> new Date("08/13/2018");
Mon Aug 13 2018 00:00:00 GMT-0700 (Pacific Daylight Time)
```
A potential workaround would be to use a different format in the XML exchanged with the server.

**Comment by 7h3ju57** [comment]
I can confirm, your fix worked, dates are coming up properly now.
Thank you so much.

**Comment by jaragunde** [comment]
Thanks for reporting and testing the fix!

**Comment by jaragunde** [comment]
Reviewed at #460:
```
commit 9f129d39e8783116bc53279e7a4fa00140fedeb3
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Wed Aug 14 09:06:37 2019 -0700

    [#459] Fix date displayed in user tasks report.
    
    Dates were received from the server in Y-m-d format, which assumes the
    UTC time zone [1] and the time 0:00. When translated to local time in
    areas west of the UTC, they became one day less and, for that reason,
    dates displayed were wrong.
    
    Worked around the problem by using a different date format without
    these implications.
    
    [1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#Differences_in_assumed_time_zone

```
