### ISSUE TITLE
3 second before interface usability when viewing a day

### ISSUE THREAD

**Issue by mrobinson** [Igalia/phpreport#506]
When viewing and editing a particular day there is a significant delay when showing pre-existing tasks or having the ability to add new tasks. From the looks of it, the UI is waiting for something before firing off the necessary XMLHttpRequests. It's likely that these should be triggered ASAP during page loading.

![Screenshot from 2021-08-11 17-55-19](https://user-images.githubusercontent.com/13536/129063435-f5980d75-1b11-4ca5-872f-38c8d8053d15.png)

**Comment by jaragunde** [comment]
About the calls that are fired in last place:
* GetOpenTaskStories is not used any more and has been recently removed.
* GetProjectsService fills the projects combo box for every task. It could be more efficient, but it shouldn't slow down the load of the list of tasks itself, they load with the project combo blank for a while.

All in all, I think we should make the call to getUserTasksService earlier, it's the key piece of data we need in this page and it seems to be fetched with some delay.

**Comment by jaragunde** [comment]
The main reason of delay for the call to getUserTasksService is that it happens inside the Ext.onReady callback.

The code that runs after the store is loaded (its `load` listener) does need the document to be ready, but we could have fetched the data earlier.

**Comment by jaragunde** [comment]
Reviewed in #571. Not sure if this will solve the problem, feel free to reopen.
```
commit 353ab131d8f214a91fbfd8d942f8d0974b62fb05 
Merge: df763403 5234f389
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Mon Mar 28 10:33:58 2022 +0200

    [#506] Speed up tasks page.
    
    Merge pull request #571 from Igalia/speed-up-tasks

commit 5234f389c3c3a4858f804f571f5f7f058f9aac08 
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Mon Mar 14 12:45:05 2022 +0100

    [#506] Move summaryStore var outside of the onReady event.
    
    The tasksStore makes use of summaryStore in its save listener, but it
    couldn't because summaryStore was still inside the onReady scope.

commit b6192481380675d476b95ffcedd5437b8c302cf0
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Mon Mar 14 12:34:14 2022 +0100

    [#506] Setup of tasks store outside of onReady event.
    
    This allows fetching the tasks earlier, speeding up the time until
    the page is fully interactive.
    
    The patch looks a bit messy but it mainly just moves the code to setup
    the TaskStore object and the associated HttpProxy outside of the
    onReady event. We take the chance to to rename these variables more
    appropriately, and to fix some wrong indentation.
    
    The load callback of the store does need to be run after the page is
    ready, so we wrap its code inside Ext.onReady().
```
