### ISSUE TITLE
Minification failure

### ISSUE THREAD

**Issue by jaragunde** [Igalia/phpreport#585]
When running the minification process on my development box, I'm getting an error in the tasks page: `Uncaught TypeError: this.monthPicker is null`. The error is located in the datepickerplus component.

I think it must be related with software versions. My software:
* Fedora 34
* uglify-js 3.15.3

We have to be aware of this reproducing in production servers, it currently doesn't. They use uglify-js 3.12.8.

As a workaround, removing the `-c -m` flags fixes the problem. This change produces slightly heavier JS files (from ~700 KB to ~900 in tasks page).

**Comment by jaragunde** [comment]
Update: it's only needed to remove `-c`. The JS used in the tasks page weights ~800 KB in this case.

**Comment by anarute** [comment]
The production server now uses `uglify-js 3.15.4` so I temporarily committed to remove the `-c` flag there until we figure a better solution.

**Comment by jaragunde** [comment]
Reviewed in PR#587:
```
commit 4c7a338786ff3e3eaa5f778da349bf286762974a 
Author: Jacobo Aragunde Pérez <jaragunde@igalia.com>
Date:   Wed May 25 12:46:41 2022 +0200

    [#585] Workaround for minification error in tasks page.
    
    Disable `-c` parameter in UglifyJS to prevent the error. This
    increases the output size a bit, but only slightly (from ~700 KB to
    ~800 in tasks page).
    
    Also write down the minimum UglifyJS version number known to prevent
    problems with the most modern JS syntax features.

```
