### ISSUE TITLE
Implement basic layout and sidebars

### ISSUE THREAD

**Issue by anarute** [Igalia/phpreport#661]
The layout is split in 3 parts: 2 sidebars and a main content section.

Both left and right sidebars are collapsible.

Follow design specs from: https://xd.adobe.com/view/9cfeca6e-f42a-44ff-9643-d5a73a0ef076-c9ad/

**Comment by dmtrek14** [comment]
Requirements:
- Left sidebar contains the main application menu as well as light/dark toggle. The 'Reports' menu item will have a submenu with the following items: 'User Tasks', 'User Details', 'Project Details'. There may be more links in the future
- The left sidebar doesn't fully collapse - it collapses down to a much thinner version of itself that shows only the icons and the button to collapse/expand the menu
- The layout should be as mobile-friendly as possible. Ideally, the main app navigation (which is the left menu on desktop) would be on the top in a mobile layout and be collapsed in a way that makes sense for mobile. Perhaps the main menu is something that is sticky to the top on a smaller device and expandable. Then the main content. Then the work summary (which is on the right on desktop) could be sticky on the bottom on a smaller device and expandable
- The right panel will be used for other pages in addition to this one and probably contain different information/functionality, so we'll need to be able to pass in the child components to the right panel that will be needed on a given page.
- The main content will have the following components: 
  - A button group for selecting day/week/month views
  - A datepicker for selecting the date
  - A button to allow the user to select 'today' without having to use the datepicker
  - The day/week/month view components
