### ISSUE TITLE
Timer implementation

### ISSUE THREAD

**Issue by dmtrek14** [Igalia/phpreport#687]
Requirements:
- Starting the timer will fill the 'From' field with the time on which the timer was started
- Ending the timer will fill the 'To' field with the time at which the timer was stopped; it will also save the task and clear the form
- The same button will be used for 'start' and 'stop'. We will change the button text and the icon
- If someone is using the timer, we will disable the To/From fields since having those active in addition to the timer would cause some issues. 
- Someone should be able to be using the timer for an ongoing task, but also be able to edit another task without the two things interfering with each other.
- If possible, it would be nice for it to persist between refreshes or if user navigates away and back. Toggl has something like this and it's a nice bit of functionality. 

This one feels like it will need some tests to ensure proper functionality

**Comment by anarute** [comment]
@negreirosleo I was testing the timer today and noticed that it doesn't keep track of time when the tab is not active. It counts for a little while only and then when you go back to the tab, it looks as it's tracking but it only recorded a few minutes.

I don't know how to solve it but we need a more robust implementation that keeps track even if the application is not focused.
